name: Python CI for SmartPresenter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install pytest pytest-html

    - name: Start mock Flask server
      run: |
        nohup python app/mock_device.py > flask.log 2>&1 &
        sleep 3

    - name: Start mock TCP server
      run: |
        nohup python app/mock_tcp_server.py > tcp.log 2>&1 &
        sleep 3

    - name: Run pytest
      run: |
        pytest tests --html=report.html --self-contained-html

    - name: Upload HTML test report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: report.html
